main/models.py
from main import db, bcrypt
from datetime import datetime
from marshmallow import fields, Schema, validate
from sqlalchemy import func


class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String, unique=True, nullable=False)
    hashed_password = db.Column(db.LargeBinary(80), nullable=False)
    authenticated = db.Column(db.Boolean, default=False)
    registered_on = db.Column(db.DateTime, nullable=True)
    role = db.Column(db.String, default='user')

    def __init__(self, email, plaintext_password, role='user'):
        self.email = email
        self.hashed_password = bcrypt.generate_password_hash(plaintext_password)
        self.authenticated = False
        self.registered_on = datetime.now()
        self.role = role

    def set_password(self, plaintext_password):
        self.hashed_password = bcrypt.generate_password_hash(plaintext_password)

    def is_correct_password(self, plaintext_password):
        return bcrypt.check_password_hash(self.hashed_password, plaintext_password)

    @property
    def is_authenticated(self):
        return self.authenticated

    @property
    def is_active(self):
        return True

    # @property
    # def is_anonymous(self):
    #    return False

    def get_id(self):
        return str(self.id)

    def get_email(self):
        return str(format(self.email))

    def get_role(self):
        return str(format(self.role))

    def to_json(self):
        return {"id": format(self.id),
                "email": format(self.email)}

    @staticmethod
    def get_all_users():
        return User.query.all()

    @staticmethod
    def get_all_users_count():
        return User.query.count()

    @staticmethod
    def get_auth_user_count():
        return User.query.filter_by(authenticated=1).count()

    @staticmethod
    def get_one_user(id):
        return User.query.get(id)

    @staticmethod
    def get_user_by_email(email):
        return User.query.filter_by(email=email).first()

    def __repr__(self):
        return '<User {}>'.format(self.email)


# class UserSchema(Schema):
#     id = fields.Int(dump_only=True)
#     email = fields.Email(required=True, validate=validate.Email(error="Invalid email address provided"))
#     hashed_password = fields.Str(required=True, validate=[validate.Length(min=2, max=8)])
#     registered_on = fields.DateTime(dump_only=True)
#     modified_at = fields.DateTime(dump_only=True)
#     authenticated = fields.Boolean(dump_only=True)

class UserSchema(Schema):
    class Meta:
        # exposed fields
        fields = ('id', 'email', 'registered_on', 'authenticated')


class Record(db.Model):
    __tablename__ = 'records'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    ca_weight = db.Column(db.Float, unique=True, nullable=False)
    ca_height = db.Column(db.Integer, unique=True, nullable=False)
    ca_gender = db.Column(db.Integer, unique=True, nullable=False)
    ca_age = db.Column(db.Integer, unique=True, nullable=False)
    ca_bmi = db.Column(db.Float, unique=True, nullable=False)
    ca_recommend = db.Column(db.String, unique=True, nullable=False)
    ca_bmi = db.Column(db.Float, unique=True, nullable=False)
    created_on = db.Column(db.DateTime, nullable=True)

    def __init__(self, ca_weight, ca_height, ca_gender, ca_age, ca_bmi, ca_recommend):
        self.ca_weight = ca_weight
        self.ca_height = ca_height
        self.ca_gender = ca_gender
        self.ca_age = ca_age
        self.ca_bmi = ca_bmi
        self.ca_recommend = ca_recommend
        self.created_on = datetime.now()

main/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt


# ####### Configurations #########

db = SQLAlchemy()
bcrypt = Bcrypt()
login = LoginManager()
login.login_view = "main.login"


def create_app(config_filename=None):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_pyfile(config_filename)
    initialize_extensions(app)
    register_blueprints(app)
    return app


def initialize_extensions(app):
    db.init_app(app)
    bcrypt.init_app(app)
    login.init_app(app)

    # Flask-Login configuration
    from main.models import User

    @login.user_loader
    def load_user(user_id):
        return User.query.filter(User.id == int(user_id)).first()


def register_blueprints(app):
    from main.rest import blueprint
    app.register_blueprint(blueprint, url_prefix='/api')

    from main.uiapp import bp
    app.register_blueprint(bp)

main/blueprints/__init__.py
#!/usr/bin/python

main/blueprints/page/__init__.py
#!/usr/bin/python
from main.blueprints.page.views import page
from main.blueprints.page.views import calc

main/blueprints/page/templates/__init__.py
#!/usr/bin/python

main/blueprints/page/templates/calc/__init__.py
#!/usr/bin/python

main/blueprints/page/views.py
#!/usr/bin/python
from flask import Blueprint, render_template, request

page = Blueprint('page', __name__, template_folder='templates')
calc = Blueprint('calc', __name__, template_folder='templates')


@page.route('/')
def home():
    return render_template('page/home.html')


@page.route('/terms')
def terms():
    return render_template('page/terms.html')


@page.route('/privacy')
def privacy():
    return render_template('page/privacy.html')


@page.route('/FAQ')
def FAQ():
    return render_template('page/FAQ.html')


@calc.route('/calculator', methods=['GET', 'POST'])
def calculator():
    bmi = ''
    recommend = ''
    if request.method == 'POST' and 'ca_weight' in request.form:
        weight = float(request.form.get('ca_weight'))
        height = float(request.form.get('ca_height'))
        bmi = calc_bmi(weight, height)
        if bmi > 0:
            if bmi <= 16:
                recommend = "You are very underweight."
            elif bmi <= 18.5:
                recommend = "You are underweight."
            elif bmi <= 25:
                recommend = "Congrats! You are Healthy."
            elif bmi <= 30:
                recommend = "You are overweight"
            else:
                recommend = "You are very overweight."
        else:
            recommend = "Enter valid details!"
    return render_template("calc/calculator.html", bmi=bmi, recommend=recommend)


def calc_bmi(weight, height):
    return round((weight / ((height / 100) ** 2)), 1)
    return render_template('calc/calculator.html')


@calc.route('/info')
def info():
    return render_template('calc/info.html')


@calc.route('/test', methods=['GET', 'POST'])
def test():
    bmi2 = ''
    recommend2 = ''
    if request.method == 'POST' and 'ca_weight' in request.form:
        weight = float(request.form.get('ca_weight'))
        height = float(request.form.get('ca_height'))
        bmi2 = calc_bmi2(weight, height)
        if bmi2 > 0:
            if bmi2 <= 16:
                recommend2 = "You are very underweight."
            elif bmi2 <= 18.5:
                recommend2 = "You are underweight."
            elif bmi2 <= 25:
                recommend2 = "Congrats! You are Healthy."
            elif bmi2 <= 30:
                recommend2 = "You are overweight"
            else:
                recommend2 = "You are very overweight."
        else:
            recommend2 = "Enter valid details!"
    return render_template("calc/test.html", bmi2=bmi2, recommend2=recommend2)


def calc_bmi2(weight, height):
    return round((weight / ((height / 100) ** 2)), 1)
    return render_template('calc/test.html')

main/templates/dashboard.html
{% extends 'layouts/base.html' %}

{% block title %}Dashboard{% endblock %}
{% block meta_description %}Fitness Calculator Website is a Flask CRUD Project to demonstrate understanding of DevOps process. {% endblock %}
{% block body %}
  <th class="container sm-margin-top">
    <div class="row text-center lg-margin-bottom">
       <h1>Welcome to Fitness Calculator!</h1>
      <div class="text-muted">
          <h2>Hi, {{ current_user.email }}</h2>
          <h2>Your ID is: {{ current_user.id }}</h2>
      </div>
    </div>
  </th>
<h4>Registered Users:</h4>
    <table class="table">
                  <thead>
                  <tr>
                      <th scope="col">ID</th>
                      <th scope="col">Email</th>
                      <th scope="col">Registered Date</th>
                  </tr>
                  </thead>
                  <tbody>

                    {% for row in rows %}
                        <tr>
                          <td data-title="Id">{{row["id"]}}</td>
                          <td data-title="Email">{{row["email"]}}</td>
                            <td data-title="Registered">{{row["registered_on"]}}</td></tr>
                     {% endfor %}

    </tbody>
    </table>
            <br><br>
           <p align="center" class="bottom"><a href="{{ url_for('main.logout')}}">Logout Here</a></p>
             <!--p align="center" class="bottom"> <a href = "/">Go back to Home page</a> </p-->
      </div>
    </div>
  </div>
  </div>
{% endblock %}

main/templates/home.html
{% extends 'layouts/base.html' %}

{% block title %}Fitness Calculator{% endblock %}
{% block meta_description %}Fitness Calculator Website is a Flask CRUD Project to demonstrate understanding of DevOps process. {% endblock %}

{% block body %}
  <div class="container sm-margin-top">
    <div class="row text-center lg-margin-bottom">
       <h1>Welcome to Fitness Calculator!</h1>
      <h3 class="text-muted">
        After a quick registration you will be able to calculate following information:
      </h3><br>
            <p>* Your BMI (Body Mass Index)</p>
            <p>* Your BFM (Body Fat Mass)</p>
            <p>* Your LBM (Lean Body Mass)</p>
            <p>* Your Daily Calories Intake</p>
            <p>* Recommended Fitness Program</p>
        <hr>
    <div class="row text-center">
      <div class="col-lg-4">
        <i class="fa fa-fw fa-4x fa-calculator text-primary"></i>
        <h2>Finess Calculator</h2>
        <p class="text-muted">Get real info about your body.</p>
        <p>
          <a href="/login" class="btn btn-default">Login</a>
        </p>
      </div>
      <div class="col-lg-4">
        <i class="fa fa-fw fa-4x fa-user text-primary"></i>
        <h2>Training Program</h2>
        <p class="text-muted">Especially for you.</p>
        <p>
          <a href="/register" class="btn btn-default">Sign up</a>
        </p>
      </div>
      <div class="col-lg-4">
        <i class="fa fa-fw fa-4x fa-coffee text-primary"></i>
        <h2>Nutrition Menu</h2>
        <p class="text-muted">Diet becomes your Life Style.</p>
        <p>
          <a href="/register" class="btn btn-default">Sign up</a>
        </p>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

main/templates/index.html
{% extends 'layouts/base.html' %}

{% block title %}Fitness Calculator{% endblock %}
{% block meta_description %}Fitness Calculator Website is a Flask CRUD Project to demonstrate understanding of DevOps process. {% endblock %}

{% block body %}
  <div class="container sm-margin-top">
    <div class="row text-center lg-margin-bottom">
       <h1>Welcome to Fitness Calculator!</h1>
      <h3 class="text-muted">
        After a quick registration you will be able to calculate following information:
      </h3><br>
            <p>* Your BMI (Body Mass Index)</p>
            <p>* Your BFM (Body Fat Mass)</p>
            <p>* Your LBM (Lean Body Mass)</p>
            <p>* Your Daily Calories Intake</p>
            <p>* Recommended Fitness Program</p>
        <hr>
    <div class="row text-center">
      <div class="col-lg-4">
        <i class="fa fa-fw fa-4x fa-calculator text-primary"></i>
        <h2>Finess Calculator</h2>
        <p class="text-muted">Get real info about your body.</p>
        <p>
          <a href="/login" class="btn btn-default">Login</a>
        </p>
      </div>
      <div class="col-lg-4">
        <i class="fa fa-fw fa-4x fa-user text-primary"></i>
        <h2>Training Program</h2>
        <p class="text-muted">Especially for you.</p>
        <p>
          <a href="/register" class="btn btn-default">Sign up</a>
        </p>
      </div>
      <div class="col-lg-4">
        <i class="fa fa-fw fa-4x fa-coffee text-primary"></i>
        <h2>Nutrition Menu</h2>
        <p class="text-muted">Diet becomes your Life Style.</p>
        <p>
          <a href="/register" class="btn btn-default">Sign up</a>
        </p>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

main/templates/layouts/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="{% block meta_description %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/bootstrap.min.css') }}">
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/main.css') }}">
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/font-awesome.min.css') }}">
    <script src="https://code.jquery.com/jquery-1.12.2.min.js"
            integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="
            crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
                  data-toggle="collapse" data-target="#navbar"
                  aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="{{ url_for('main.home') }}">
            <img src="{{ url_for('static', filename='images/logo.png') }}"
                 class="img-responsive"
                 width="229" height="50" title="Calculator" alt="Calculator"/>
          </a>
        </div>
      </div>
    </nav>

    <main class="container">
      <div class="md-margin-top">{% block heading %}{% endblock %}</div>
      {% block body %}{% endblock %}
    </main>

    <footer class="footer text-center">
      <div class="container">
        <ul class="list-inline">
          <li class="text-muted">Fitness Calculator &copy; 2022</li>
          <li><a href="{{ url_for('page.privacy') }}">Privacy Policy</a></li>
          <li><a href="{{ url_for('page.terms') }}">Terms of Service</a></li>
            <li><a href="{{ url_for('page.FAQ') }}">FAQ</a></li>
            <li><a href="{{ url_for('calc.calculator') }}">Calculator</a></li>
        </ul>
      </div>
    </footer>

    <script
      src="{{ url_for('static', filename='scripts/vendor/bootstrap.min.js') }}">
    </script>
  </body>
</html>

main/templates/login.html
{% extends 'layouts/base.html' %}

{% block title %}Login{% endblock %}
{% block meta_description %}Fitness Calculator Website is a Flask CRUD Project to demonstrate understanding of DevOps process. {% endblock %}

{% block body %}
  <div class="container sm-margin-top">
    <div class="row text-center lg-margin-bottom">
       <h1>Welcome to Fitness Calculator</h1>
      <h3 class="text-muted">
      </h3><br><br><br><br>
             <div class="header">
                <h1>Login</h1>
             </div>
            <div class="msg">{{ msg }}</div>
            <h2 class="word">
                <!--form action="{{ url_for('main.login') }}" method="post"-->
                <form action="" method="post">
                  <!--div class="msg">{{ msg }}</div-->
                    <input id="email" name="email" type="text" placeholder="Enter Email" class="textbox"/></br></br>
                    <input id="password" name="password" type="password" placeholder="Enter Password" class="textbox"/></br></br>
                    <input type="submit" class="btn" value="Log Me In"></br></br>
                </form>
            </h2>
            <p align="center" class="bottom">New User?  <a class="bottom" href="{{url_for('main.register')}}"> Sign up Here</a></p>
          <!--/div-->
      </div>
    </div>
  </div>
  </div>
{% endblock %}

main/templates/register.html
{% extends 'layouts/base.html' %}

{% block title %}Register{% endblock %}
{% block meta_description %}Fitness Calculator Website is a Flask CRUD Project to demonstrate understanding of DevOps process. {% endblock %}

{% block body %}
  <div class="container sm-margin-top">
    <div class="row text-center lg-margin-bottom">
       <h1>Welcome to Fitness Calculator!</h1>
      <h3 class="text-muted">
      </h3><br><br><br><br>
             <div class="header">
         <div class="header">
            <h1>Register</h1>
         </div>
             <div class="msg">{{ msg }}</div>
        <h2 class="word">
        <form action="" method = "POST">

            <input id="email" name="email" type="text" placeholder="Enter Your Email-Id" class="textbox"/></br></br>
            <input id="password" name="password" type="password" placeholder="Enter Your Password" class="textbox"/></br></br>
            <input type="submit" class="btn" value="Sign Me Up"></br></br>
        </form>
        </h2>
        <p align="center" class="bottom">Already Have an Account?  <a class="bottom" href="{{url_for('main.login')}}">Log in Here</a></p>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

main/templates/test.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="{% block meta_description %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/bootstrap.min.css') }}">
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/main.css') }}">
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/font-awesome.min.css') }}">
    <script src="https://code.jquery.com/jquery-1.12.2.min.js"
            integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="
            crossorigin="anonymous"></script>
  <title>Welcome</title>
  </head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
                  data-toggle="collapse" data-target="#navbar"
                  aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="{{ url_for('main.login') }}">
            <img src="{{ url_for('static', filename='images/logo.png') }}"
                 class="img-responsive"
                 width="229" height="50" title="Calculator" alt="Calculator"/>
          </a>
        </div>
      </div>
    </nav>
  <div class="container sm-margin-top">
    <div class="row text-center lg-margin-bottom">
       <h1>Welcome to Fitness Calculator</h1>
      <h3 class="text-muted">
        After a quick registration you will be able to calculate following information:
      </h3><br>
            <p>* Your BMI (Body Mass Index)</p>
            <p>* Your BFM (Body Fat Mass)</p>
            <p>* Your LBM (Lean Body Mass)</p>
            <p>* Your Daily Calories Intake</p>
            <p>* Recommended Fitness Program</p>
        <hr>
    <div class="row text-center">
      <div class="col-lg-4">
        <i class="fa fa-fw fa-4x fa-calculator text-primary"></i>
        <h2>Finess Calculator</h2>
        <p class="text-muted">Get real info about your body.</p>
        <p>
          <a href="/login" class="btn btn-default">Login</a>
        </p>
      </div>
      <div class="col-lg-4">
        <i class="fa fa-fw fa-4x fa-user text-primary"></i>
        <h2>Training Program</h2>
        <p class="text-muted">Especially for you.</p>
        <p>
          <a href="/register" class="btn btn-default">Sign up</a>
        </p>
      </div>
      <div class="col-lg-4">
        <i class="fa fa-fw fa-4x fa-coffee text-primary"></i>
        <h2>Nutrition Menu</h2>
        <p class="text-muted">Diet becomes your Life Style.</p>
        <p>
          <a href="/register" class="btn btn-default">Sign up</a>
        </p>
      </div>
    </div>
  </div>
  </div>
        <footer class="footer text-center">
      <div class="container">
        <ul class="list-inline">
          <li class="text-muted">Fitness Calculator &copy; 2022</li>
          <li><a href="{{ url_for('main.privacy') }}">Privacy Policy</a></li>
          <li><a href="{{ url_for('main.terms') }}">Terms of Service</a></li>
            <li><a href="{{ url_for('main.FAQ') }}">FAQ</a></li>
        </ul>
      </div>
    </footer>
    <script
      src="{{ url_for('static', filename='scripts/vendor/bootstrap.min.js') }}">
    </script>
    </body>
</html>