main/blueprints/page/__init__.py
#!/usr/bin/python
from main.blueprints.page.views import page
from main.blueprints.page.views import calc

main/blueprints/page/templates/__init__.py
#!/usr/bin/python

main/blueprints/page/templates/calc/__init__.py
#!/usr/bin/python

main/blueprints/page/views.py
#!/usr/bin/python
from flask import Blueprint, render_template, request

page = Blueprint('page', __name__, template_folder='templates')
calc = Blueprint('calc', __name__, template_folder='templates')


@page.route('/')
def home():
    return render_template('page/home.html')


@page.route('/terms')
def terms():
    return render_template('page/terms.html')


@page.route('/privacy')
def privacy():
    return render_template('page/privacy.html')


@page.route('/FAQ')
def FAQ():
    return render_template('page/FAQ.html')


@calc.route('/calculator', methods=['GET', 'POST'])
def calculator():
    bmi = ''
    recommend = ''
    if request.method == 'POST' and 'ca_weight' in request.form:
        weight = float(request.form.get('ca_weight'))
        height = float(request.form.get('ca_height'))
        bmi = calc_bmi(weight, height)
        if bmi > 0:
            if bmi <= 16:
                recommend = "You are very underweight."
            elif bmi <= 18.5:
                recommend = "You are underweight."
            elif bmi <= 25:
                recommend = "Congrats! You are Healthy."
            elif bmi <= 30:
                recommend = "You are overweight"
            else:
                recommend = "You are very overweight."
        else:
            recommend = "Enter valid details!"
    return render_template("calc/calculator.html", bmi=bmi, recommend=recommend)


def calc_bmi(weight, height):
    return round((weight / ((height / 100) ** 2)), 1)
    return render_template('calc/calculator.html')


@calc.route('/info')
def info():
    return render_template('calc/info.html')


@calc.route('/test', methods=['GET', 'POST'])
def test():
    bmi2 = ''
    recommend2 = ''
    if request.method == 'POST' and 'ca_weight' in request.form:
        weight = float(request.form.get('ca_weight'))
        height = float(request.form.get('ca_height'))
        bmi2 = calc_bmi2(weight, height)
        if bmi2 > 0:
            if bmi2 <= 16:
                recommend2 = "You are very underweight."
            elif bmi2 <= 18.5:
                recommend2 = "You are underweight."
            elif bmi2 <= 25:
                recommend2 = "Congrats! You are Healthy."
            elif bmi2 <= 30:
                recommend2 = "You are overweight"
            else:
                recommend2 = "You are very overweight."
        else:
            recommend2 = "Enter valid details!"
    return render_template("calc/test.html", bmi2=bmi2, recommend2=recommend2)


def calc_bmi2(weight, height):
    return round((weight / ((height / 100) ** 2)), 1)
    return render_template('calc/test.html')

main/blueprints/page/templates/calc/calculator.html
{% extends 'layouts/base.html' %}

{% block title %}Calculator{% endblock %}
{% block meta_description %}Fitness Calculator Website is a Flask CRUD Project to demonstrate understanding of DevOps process. {% endblock %}

{% block body %}
  <div class="container sm-margin-top">
    <div class="row text-center lg-margin-bottom">
       <h1>Welcome to BMI Calculator!</h1>
      <h3 class="text-muted">
      </h3><br><br>
                        <div style="height:auto!important;height:20px;border:1px ;font-size:16px;">For more info, what BMI is, click
                    <label id="method" type="button" style="color:dodgerblue; width:100px;" onclick="let sta = document.getElementById('popTitle');
                          let mod = document.getElementById('method');
                          if(sta.style.display == 'none')
                          {
                          sta.style.display='';
                          mod.innerText='close';
                          mod.innerHTML='close';
                          }
                        else
                          {
                          sta.style.display='none';
                          mod.innerText='here';
                          mod.innerHTML='here';};">here

                    </label>

                    <div id="popTitle" visibility="hidden" style="display:none;">
                        <pre style="word-break:break-all;width:510px;height:100px;color:dodgerblue;">
Body mass index (BMI) is a measure of body fat based on your
weight in relation to your height, and applies to most adult
men and women aged 19 and over. For children and young people
aged 2 to 18, the BMI calculation takes into account age
and gender as well as height and weight.
                            </pre>
                    </div>
        <div class="header">
            <h2>Please, fill the *required fields:</h2>
        </div>
        <div class="msg">{{ msg }}</div>
        <h2 class="word">
            <form action="" method = "POST">
                <h4>Your ID is: {{ current_user.id }}</h4>
                <input id="client_id" name="client_id" required type="number" min="1" placeholder="*Your ID:" class="textbox" oninput="check(this)"/></br></br>
                <input id="ca_weight" name="ca_weight" required type="number" min="1" placeholder="*Weight in kg:" class="textbox" oninput="check(this)"/></br></br>
                <input id="ca_height" name="ca_height" required type="number" min="1" placeholder="*Height in cm:" class="textbox" oninput="check(this)"/></br></br>
                <input id="ca_age" name="ca_age" required type="number" min="1" placeholder="*Your Age:" class="textbox" oninput="check(this)"/></br></br>
                <label>Gender:</label>
                <select>
                    <option value = "1">Male</option>
                    <option value = "0">Female</option>
                </select><br><br>
                <button type="submit" class="btn" value="Submit">Calculate</button></br></br>
            </form>
            <script>
                 function check(input) {
                   if (input.value == 0) {
                     input.setCustomValidity('The number must not be zero.');
                   } else {
                     // input is fine -- reset the error message
                     input.setCustomValidity('');
                   }
                 }
         </script>
            {% if bmi %}
	    <p>{% print("Your BMI is: {}".format(bmi)) %}</p>
            <p>{% print("{}".format(recommend)) %}</p>
            {% endif %}
        </h2>
<br>
                            <p align="center" class="bottom"><a href="{{ url_for('calc.info')}}">BMI Tables</a></p>
                            <br>

                 <p align="center" class="bottom">New User, no ID?  <a class="bottom" href="{{url_for('main.register')}}"> Sign up Here</a></p>
                 <p>or</p>
                 <p align="center" class="bottom"><a href="{{ url_for('main.logout')}}">Logout Here</a></p>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

main/blueprints/page/templates/calc/test.html
{% extends 'layouts/base.html' %}

{% block title %}Calculator{% endblock %}
{% block meta_description %}Fitness Calculator Website is a Flask CRUD Project to demonstrate understanding of DevOps process. {% endblock %}

{% block body %}
  <div class="container sm-margin-top">
    <div class="row text-center lg-margin-bottom">
       <h1>Welcome to BMI Calculator!</h1>
      <h3 class="text-muted">
      </h3><br><br>
                        <div style="height:auto!important;height:20px;border:1px ;font-size:16px;">For more info, what BMI is, click
                    <label id="method" type="button" style="color:dodgerblue; width:100px;" onclick="let sta = document.getElementById('popTitle');
                          let mod = document.getElementById('method');
                          if(sta.style.display == 'none')
                          {
                          sta.style.display='';
                          mod.innerText='close';
                          mod.innerHTML='close';
                          }
                        else
                          {
                          sta.style.display='none';
                          mod.innerText='here';
                          mod.innerHTML='here';};">here

                    </label>

                    <div id="popTitle" visibility="hidden" style="display:none;">
                        <pre style="word-break:break-all;width:510px;height:100px;color:dodgerblue;">
Body mass index (BMI) is a measure of body fat based on your
weight in relation to your height, and applies to most adult
men and women aged 19 and over. For children and young people
aged 2 to 18, the BMI calculation takes into account age
and gender as well as height and weight.
                            </pre>
                    </div>
        <div class="header">
            <h2>Please, fill the *required fields:</h2>
        </div>
        <div class="msg">{{ msg }}</div>
        <h2 class="word">
            <form action="" method = "POST">
                <h4>Your ID is: {{ current_user.id }}</h4>
                <input id="client_id" name="client_id" required type="number" min="1" placeholder="*Your ID:" class="textbox" oninput="check(this)"/></br></br>
                <input id="ca_weight" name="ca_weight" required type="number" min="1" placeholder="*Weight in kg:" class="textbox" oninput="check(this)"/></br></br>
                <input id="ca_height" name="ca_height" required type="number" min="1" placeholder="*Height in cm:" class="textbox" oninput="check(this)"/></br></br>
                <input id="ca_age" name="ca_age" required type="number" min="1" placeholder="*Your Age:" class="textbox" oninput="check(this)"/></br></br>
                <label>Gender:</label>
                <select>
                    <option value = "1">Male</option>
                    <option value = "0">Female</option>
                </select><br><br>
                <button type="submit" class="btn" value="Submit">Calculate</button></br></br>
            </form>
            <script>
                 function check(input) {
                   if (input.value == 0) {
                     input.setCustomValidity('The number must not be zero.');
                   } else {
                     // input is fine -- reset the error message
                     input.setCustomValidity('');
                   }
                 }
         </script>
            {% if bmi2 %}
	    <p>{% print("Your BMI is: {}".format(bmi2)) %}</p>
            <p>{% print("{}".format(recommend2)) %}</p>
            {% endif %}
        </h2>
<br>
                            <p align="center" class="bottom"><a href="{{ url_for('calc.info')}}">BMI Tables</a></p>
                            <br>

                 <p align="center" class="bottom">New User, no ID?  <a class="bottom" href="{{url_for('main.register')}}"> Sign up Here</a></p>
                 <p>or</p>
                 <p align="center" class="bottom"><a href="{{ url_for('main.logout')}}">Logout Here</a></p>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

main/blueprints/page/templates/page/FAQ.html
{% extends 'layouts/base.html' %}

{% block title %}FAQ{% endblock %}
{% block heading %}<h2>Frequently Asked Questions</h2>{% endblock %}

{% block body %}
  <p>
    In progress....<i class="fa fa-cog fa-spin fa-3x fa-fw"></i>
<span class="sr-only">Loading...</span>
    <a href="http://{{ config.get('SERVER_NAME') }}">
      http://{{ config.get('SERVER_NAME') }}
    </a>.
  </p>
  <small class="text-muted">Last updated September 10th 2022</small>
{% endblock %}s

main/blueprints/page/templates/page/home.html
{% extends 'layouts/base.html' %}

{% block title %}Test your luck against the roll of the dice{% endblock %}
{% block meta_description %}Compete against yourself and others by guessing the
outcome of a dice roll. Win points and dominate the leaderboard.{% endblock %}

{% block body %}
  <div class="container sm-margin-top">
    <div class="row text-center lg-margin-bottom">
      <h1>Welcome to Fitness Web Application!</h1>
      <h3 class="text-muted">
        After a quick registration you will be able to calculate following information:
      </h3><br>
            <p>* Your BMI (Body Mass Index)</p>
            <p>* Your BFM (Body Fat Mass)</p>
            <p>* Your LBM (Lean Body Mass)</p>
            <p>* Your Daily Calories Intake</p>
            <p>* Recommended Fitness Program</p>
        <hr>
    <div class="row text-center">
      <div class="col-lg-4">
        <i class="fa fa-fw fa-4x fa-calculator text-primary"></i>
        <h2>Finess Calculator</h2>
        <p class="text-muted">Get real info about your body.</p>
        <p>
          <a href="#" class="btn btn-default">Sign up</a>
        </p>
      </div>
      <div class="col-lg-4">
        <i class="fa fa-fw fa-4x fa-user text-primary"></i>
        <h2>Training Program</h2>
        <p class="text-muted">Especially for you.</p>
        <p>
          <a href="#" class="btn btn-default">Sign up</a>
        </p>
      </div>
      <div class="col-lg-4">
        <i class="fa fa-fw fa-4x fa-coffee text-primary"></i>
        <h2>Nutrition Menu</h2>
        <p class="text-muted">Diet becomes your Life Style.</p>
        <p>
          <a href="#" class="btn btn-default">Sign up</a>
        </p>
      </div>
    </div>
  </div>
{% endblock %}

main/blueprints/page/templates/page/privacy.html
{% extends 'layouts/base.html' %}

{% block title %}Privacy Policy{% endblock %}
{% block heading %}<h2>Privacy Policy</h2>{% endblock %}

{% block body %}
  <p>
    This privacy policy discloses the privacy practices for
    <a href="http://{{ config.get('SERVER_NAME') }}">
      http://{{ config.get('SERVER_NAME') }}
    </a>.<i class="fa fa-cog fa-spin fa-3x fa-fw"></i>
<span class="sr-only">Loading...</span>
  </p>
  <small class="text-muted">Last updated September 10th 2022</small>
{% endblock %}

main/blueprints/page/templates/page/terms.html
{% extends 'layouts/base.html' %}

{% block title %}Terms of Service{% endblock %}
{% block heading %}<h2>Terms of Service</h2>{% endblock %}

{% block body %}
    <p>
      By using the Fitness Calculator ("service"), you are agreeing to be bound by the
      following terms and conditions ("terms of service").
    </p>
    <p>
      Fitness Calculator, LLC ("company") reserves the right to update and change these
      terms of service without notice.
    </p>
    <p>
      Violation of any of the terms below may result in the termination of your
      account.
    </p>
    <small class="text-muted">Last updated September 10th 2022</small>
{% endblock %}